Events/Controllers/AttendanceController.cs
using Events.Core;
using Events.Core.Mappers;
using Events.Core.Models;
using Events.Core.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Events.Controllers
{
    public class AttendanceController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IEnumerable<PaymentType> _paymentTypes;
        private readonly MapAttendances _mapper;

        public AttendanceController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _mapper = new MapAttendances();
            _paymentTypes = _unitOfWork.PaymentTypes.GetPaymentTypes();
        }

        public ActionResult Add(int meetingId, string attendeeType)
        {
            if (attendeeType == AttendeeTypes.Individual)
            {
                var viewModel = new IndividualAttendanceFormViewModel() { PaymentTypes = _paymentTypes, MeetingId = meetingId };
                return View("AddIndividualAttendance", viewModel);
            }
            else if (attendeeType == AttendeeTypes.Buisness)
            {
                var viewModel = new BuisnessAttendanceFormViewModel() { PaymentTypes = _paymentTypes, MeetingId = meetingId};
                return View("AddBuisnessAttendance", viewModel);
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddIndividual(IndividualAttendanceFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("AddIndividualAttendance", viewModel);

            var checkAttendance = _unitOfWork.Attendances.GetAttendanceByMeetingIdAttendeeCode(viewModel.MeetingId, viewModel.IdentityCode);

            // Kui sellise isikukoodiga osavõtja on üritusele juba registreerinud - anname võimaluse andmeid muuta
            if (checkAttendance != null)
            {
                ViewBag.Error = "Olete üritusele juba registreerinud, soovi korral muutke andmeid";
                viewModel.Id = checkAttendance.Id;
                viewModel.PaymentTypes = _paymentTypes;
                return View("EditIndividualAttendance", viewModel);
            }

            var attendance = _mapper.MapIndividualToAttendance(viewModel);
            _unitOfWork.Attendances.AddAttendance(attendance);
            _unitOfWork.Save();

            return RedirectToAction("Details", "Meetings", new { Id = viewModel.MeetingId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddBuisness(BuisnessAttendanceFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("AddBuisnessAttendance", viewModel);

            var attendance = _mapper.MapBuisnessToAttendance(viewModel);
            _unitOfWork.Attendances.AddAttendance(attendance);
            _unitOfWork.Save();

            return RedirectToAction("Details", "Meetings", new { Id = viewModel.MeetingId });
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Error = "";
            var attendance = _unitOfWork.Attendances.GetAttendance(id);

            if (attendance == null)
                return HttpNotFound();

            if (attendance.AttendeeType == AttendeeTypes.Individual)
            {
                var viewModel = _mapper.MapToIndividualFormViewModel(attendance);
                viewModel.PaymentTypes = _paymentTypes;
                return View("EditIndividualAttendance", viewModel);
            }
            else if (attendance.AttendeeType == AttendeeTypes.Buisness)
            {
                var viewModel = _mapper.MapToBuisnessFormViewModel(attendance);
                viewModel.PaymentTypes = _paymentTypes;
                return View("EditBuisnessAttendance", viewModel);
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditIndividual(IndividualAttendanceFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("EditIndividualAttendance", viewModel);

            var attendance = _mapper.MapIndividualToAttendance(viewModel);
            _unitOfWork.Update(attendance);
            _unitOfWork.Save();

            return RedirectToAction("Details", "Meetings", new { Id = attendance.MeetingId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditBuisness(BuisnessAttendanceFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("EditBuisnessAttendance", viewModel);

            var attendance = _mapper.MapBuisnessToAttendance(viewModel);
            _unitOfWork.Update(attendance);
            _unitOfWork.Save();

            return RedirectToAction("Details", "Meetings", new { Id = attendance.MeetingId });
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var attendance = _unitOfWork.Attendances.GetAttendance(id);

            if (attendance == null)
                return HttpNotFound();

            _unitOfWork.Attendances.RemoveAttendance(attendance);
            _unitOfWork.Save();

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

    }
}

Events/Controllers/MeetingsController.cs
using Events.Core;
using Events.Core.Mappers;
using Events.Core.ViewModels;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Events.Controllers
{
    public class MeetingsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly MapMeetings _mapper;
        private readonly Helper _helper;

        public MeetingsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _mapper = new MapMeetings();
            _helper = new Helper();
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MeetingsFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            if (_helper.GetDateTime(viewModel.Date, viewModel.Time) <= DateTime.Now)
                return View(viewModel);

            var meeting = _mapper.MapFormToMeeting(viewModel);
            _unitOfWork.Meetings.AddMeeting(meeting);
            _unitOfWork.Save();

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Edit(int id)
        {
            var meeting = _unitOfWork.Meetings.GetMeeting(id);

            if (meeting == null)
                return HttpNotFound();

            if (meeting.Date < DateTime.Now)
                return RedirectToAction("Details", "Meetings", new { Id = id });

            var viewModel = _mapper.MapToMeetingsForm(meeting);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MeetingsFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            if (_helper.GetDateTime(viewModel.Date, viewModel.Time) < DateTime.Now)
                return RedirectToAction("Edit", "Meetings", new { Id = viewModel.Id });

            var meeting = _mapper.MapFormToMeeting(viewModel);
            _unitOfWork.Update(meeting);
            _unitOfWork.Save();

            return RedirectToAction("Details", "Meetings", new { Id = meeting.Id });
        }

        public ActionResult Details(int id)
        {
            var meeting = _unitOfWork.Meetings.GetMeeting(id);

            if (meeting == null)
                return HttpNotFound();

            var viewModel = _mapper.MapToDetailsViewModel(meeting);
            viewModel.Attendees = _unitOfWork.Attendances.GetAttendanceByMeetingId(id)
                .Select(a => new LowDetailAttendeeViewModel() { Id = a.Id, IdentityCode = a.IdentityCode, Name = a.Name });

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var meeting = _unitOfWork.Meetings.GetMeeting(id);

            if (meeting == null || meeting.Date <= DateTime.Now)
                return HttpNotFound();

            _unitOfWork.Meetings.RemoveMeeting(meeting);
            _unitOfWork.Save();

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
    }
}

Events/Views/Meetings/Add.cshtml
@model Events.Core.ViewModels.MeetingsFormViewModel

@{
    ViewBag.Title = "Lisa Üritus";
    ViewBag.SubTitle = "Lisa üritus";
}

@Html.Partial("_SubTitle")

<section class="row">
    <div class="col-md-6 col-md-push-2">

        @using (Html.BeginForm("Add", "Meetings", FormMethod.Post, new { @class = "form-horizontal" }))
        {

            <!-- Ürituse vormi sisu -->   
            @Html.Partial("_MeetingForm")

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    @Html.ActionLink("Tagasi", "Index", "Home", null, new { @class = "btn btn-default" })
                    <button type="submit" class="btn btn-primary">Salvesta</button>
                </div>
            </div>
        }
    </div>

</section>

Events/Views/Meetings/Details.cshtml
@model Events.Core.ViewModels.MeetingsDetailViewModel

@{
    ViewBag.Title = "Ürituse detailid";
    ViewBag.SubTitle = "Ürituse info";
}

@Html.Partial("_SubTitle")

<!-- Ürituse info -->
<section class="row">
    <div class="col-md-4 col-md-push-3">
        <table class="table table-borderless" id="meetingInfo">
            <tr>
                <th>@Html.DisplayNameFor(m => m.Name):</th>
                <td>@Html.DisplayFor(m => m.Name)</td>
            </tr>
            <tr>
                <th>@Html.DisplayNameFor(m => m.Location):</th>
                <td>@Html.DisplayFor(m => m.Location)</td>
            </tr>
            <tr>
                <th>@Html.DisplayNameFor(m => m.Date):</th>
                <td>@Html.DisplayFor(m => m.Date)</td>
            </tr>
            <tr>
                <th>@Html.DisplayNameFor(m => m.ExtraInfo):</th>
                <td>@Html.DisplayFor(m => m.ExtraInfo)</td>
            </tr>
            <tr>
                <td>
                    @if (Model.Date >= DateTime.Now)
                    {
                            @Html.ActionLink("MUUDA", "Edit", "Meetings", new { Id = Model.Id }, new { @class = "btn btn-warning btn-xs" })
                    }
                </td>
            </tr>
        </table>
    </div>
</section>

<!-- Ürituse osavõtjad -->
<section class="row">
    <div class="col-md-6 col-md-push-3">
        <h3>Osavõtjad:</h3>
        <table class="table table-borderless" id="attendees">

            @foreach (var item in Model.Attendees)
            {
                <tr>
                    <td>@Html.ActionLink(item.Name, "Edit", "Attendance", new { Id = item.Id }, null)</td>
                    <td>@item.IdentityCode</td>
                    <td><span data-id="@item.Id" data-name="@item.Name" class="glyphicon glyphicon-remove delete-icon" aria-hidden="true"></span></td>
                </tr>
            }

        </table>
    </div>
</section>

<section class="row">
    <div class="col-md-6 col-md-push-3">
        @Html.ActionLink("Tagasi", "Index", "Home", null, new { @class = "btn btn-default" })

        <!-- If the meeting has not yet been hold, then you can add attendances -->
        @if (Model.Date >= DateTime.Now)
        {
            <div class="btn-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Lisa osavõtja <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        @Html.ActionLink("Eraisik", "Add", "Attendance", new { meetingId = Model.Id, attendeeType = "Individual" }, null)
                    </li>
                    <li>
                        @Html.ActionLink("Ettevõte", "Add", "Attendance", new { meetingId = Model.Id, attendeeType = "Buisness" }, null)
                    </li>
                </ul>
            </div>
        }

    </div>
</section>


@section Scripts 
{
    <script>

        $(document).ready(function () {

            $('#attendees td span').on('click', function () {
                DeleteEntry($(this),"Kas olete kindet, et soovite kustutada osavõtja", "/Attendance/Delete/", ajaxDelete);
            });

        });

    </script>

}

Events/Views/Meetings/Edit.cshtml
@model Events.Core.ViewModels.MeetingsFormViewModel

@{
    ViewBag.Title = "Muuda Üritust";
    ViewBag.SubTitle = "Muuda ürituse andmeid";
}


@Html.Partial("_SubTitle")

<section class="row">
    <div class="col-md-6 col-md-push-2">

        @using (Html.BeginForm("Edit", "Meetings", FormMethod.Post, new { @class = "form-horizontal" }))
        {

            @Html.HiddenFor(m => m.Id)

            <!-- Ürituse vormi sisu -->
            @Html.Partial("_MeetingForm")

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    @Html.ActionLink("Tagasi", "Details", "Meetings", new { Id = Model.Id }, new { @class = "btn btn-default" })
                    <button type="submit" class="btn btn-primary">Salvesta</button>
                </div>
            </div>
        }
    </div>

</section>

Events/Views/Meetings/_MeetingForm.cshtml
@model Events.Core.ViewModels.MeetingsFormViewModel


<!-- Ürituse lisamise/muutmise vormi keha -->

@Html.AntiForgeryToken()

<div class="form-group">
    @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10">
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name, "Nimi on kohustuslik", new { @class = "field-validation-error" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Location, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10">
        @Html.TextBoxFor(m => m.Location, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Location, "Asukoht on kohustuslik", new { @class = "field-validation-error" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Date, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10">
        @Html.TextBoxFor(m => m.Date, new { @class = "form-control datepicker" })
        @Html.ValidationMessageFor(m => m.Date, "Kuupäev on kohustuslik", new { @class = "field-validation-error" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Time, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10">
        @Html.TextBoxFor(m => m.Time, new { @class = "form-control", placeholder = "18:00" })
        @Html.ValidationMessageFor(m => m.Time, "Kellaaeg on kohustuslik ja peab olema 24h formaadis", new { @class = "field-validation-error" })
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.ExtraInfo, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10">
        @Html.TextBoxFor(m => m.ExtraInfo, new { @class = "form-control" })
    </div>
</div>